### ISSUE TITLE
Split list in font + svg

### ISSUE THREAD

**Issue by larsenwork** [vkarampinis/awesome-icons#4]
Many of us don't use fonts any more so it'd be great to quickly see which ones were fonts and which are svgs somehow.

**Comment by vkarampinis** [comment]
Some icon packs support mix formats, it will be hard to categorize them.
Maybe it will be nice to have an indicator beside each font, somehow!
Suggestions?

**Comment by larsenwork** [comment]
Either that or two lists and then just have duplicate of packs that give us both ;)

**Comment by vkarampinis** [comment]
I don't really like the duplicate list, I prefer the indicator.
Its nice to have, but  I am not quite sure yet, where to put it.

**Comment by larsenwork** [comment]
Table? The x could be an icon

| Name | Vector | Font | PNG |
|-----------------------|---|---|---|
| Material Design Icons | [x](#) | [x](#) | [x](#) |
| Font Awesome          |   | [x](#) |   |
| web.min.svg           | [x](#) |   |   |

**Comment by vkarampinis** [comment]
Hmm... not bad at all!

**Comment by vkarampinis** [comment]
closing this because I have not time to make those splits.
